<?php

namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;

use App\Models\Expense;

class ExpenseFactory extends Factory
{
    protected $model = Expense::class;

    public function definition(): array
    {
        return [
            // TODO: this is all in Latin... not sure how to generate in English?!
            'amount' => $this->faker->randomFloat(2, 2, 1_000),
            'title' => $this->faker->sentence(3),
            'date' => $this->faker->dateTimeBetween('-1 year', 'now')->format('Y-m-d'),
            'description' => $this->faker->optional()->sentence(6),
            'category' => $this->faker->randomElement([
                'Food',
                'Rent',
                'Transport',
                'Entertainment',
                'Utilities',
                'Healthcare',
                'Shopping',
                'Other'
            ]), // TODO: should be generated by AI based on title and description
        ];
    }
}
